name: docker ci

on: 
  pull_request:
    branches:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3.1.0
     - name: Build Image
       run: docker build . -t api:test
