
name: Node.js CI

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Building App
      run: npm run build --if-present
      
    - name: Run Tests
      run: npm test --if-present
